"""
Validator churn analysis: deterministic queue projection + Monte Carlo.

  1. Deterministic   – simulate exit/entry/pending queues epoch-by-epoch.
  2. Statistical     – bootstrap Monte Carlo beyond the deterministic horizon,
                       using empirical per-epoch delta distributions extracted
                       from the history file.

Run from project root:
    python3 beacon_queues/analyze_churn.py

─────────────────────────────────────────────────────────────────────────────
Key beacon-chain concepts used here
─────────────────────────────────────────────────────────────────────────────
  active_count   = active_ongoing validators (NOT including active_exiting).
  exit_count     = active_exiting + slashed.  When an exit is *scheduled*,
                   the validator leaves active_count immediately and joins
                   exit_count.  Exit_count drains later as exit_epoch deadlines
                   arrive – this does NOT further change active_count.
  entry_count    = pending_queued (waiting for activation into active_ongoing).
  pending_count  = pending_deposits (committed ETH, not yet in entry queue).
                   Flows into entry_count at the same churn rate.
─────────────────────────────────────────────────────────────────────────────
Statistical approach
─────────────────────────────────────────────────────────────────────────────
  Per-epoch deltas (3 956 samples) are split into:
    organic  – epochs with |Δactive| ≤ ORGANIC_DELTA_CAP
               (background validator turnover, no large structural event)
    event    – epochs with Δactive < -ORGANIC_DELTA_CAP
               (a large batch of voluntary exits being processed)

  Synthetic daily deltas are generated by bootstrapping (sum of
  EPOCHS_PER_DAY per-epoch samples). Two distributions are built:
    organic_daily  – from organic epochs only  → lower bound on volatility
    full_daily     – from all epochs mixed     → includes historical event rate

  Monte Carlo runs N_SIMS simulations; output is percentile bands.

  ⚠ Caveat: only 18 days of history are available.  The period captured an
  unusually large exit wave (peak exit_q ≈ 2 490).  The 'full history'
  projection may overstate the long-run event rate; the 'organic only'
  projection may understate it.  Both are shown for context.
"""

import csv
import os
import random
import statistics
from datetime import datetime, timedelta, timezone

DATA_DIR     = "data"
HISTORY_CSV  = os.path.join(DATA_DIR, "history.csv")
DET_CSV      = os.path.join(DATA_DIR, "projection_deterministic.csv")
STAT_CSV     = os.path.join(DATA_DIR, "projection_statistical.csv")

GENESIS_TIMESTAMP  = 1606824023       # Dec 1 2020, 12:00:23 UTC
SECONDS_PER_EPOCH  = 32 * 12         # 384 s
EPOCHS_PER_DAY     = 86400 // SECONDS_PER_EPOCH   # 225

# Empirically observed rates: 8 validators/epoch (both activation and exit drain)
ACTIVATION_RATE = 8
DRAIN_RATE      = 8

# Threshold between "organic" and "event" epochs:
# delta_active < -ORGANIC_DELTA_CAP  →  event (large batch exit)
ORGANIC_DELTA_CAP = 20

# Monte Carlo parameters
N_SYNTH_DAYS  = 10_000   # synthetic daily deltas pre-generated via bootstrap
N_SIMS        = 2_000
HORIZON_DAYS  = 365


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def epoch_to_dt(epoch: int) -> datetime:
    return datetime.fromtimestamp(
        GENESIS_TIMESTAMP + epoch * SECONDS_PER_EPOCH, tz=timezone.utc
    )

def fmt(dt: datetime) -> str:
    return dt.strftime("%Y-%m-%d")

def pct(sorted_vals: list, p: float) -> float:
    """p in [0, 100]; linear interpolation."""
    n = len(sorted_vals)
    if n == 0:
        return float("nan")
    idx = (n - 1) * p / 100.0
    lo  = int(idx)
    hi  = min(lo + 1, n - 1)
    return sorted_vals[lo] + (sorted_vals[hi] - sorted_vals[lo]) * (idx - lo)


# ─────────────────────────────────────────────────────────────────────────────
# Data loading
# ─────────────────────────────────────────────────────────────────────────────

def load_epoch_data(path: str) -> dict:
    """One dict per epoch (lowest slot used when epoch appears multiple times)."""
    raw: dict = {}
    with open(path, newline="") as f:
        for row in csv.DictReader(f):
            ep   = int(row["epoch"])
            slot = int(row["slot"])
            if ep not in raw or slot < raw[ep]["slot"]:
                raw[ep] = dict(
                    epoch       = ep,
                    slot        = slot,
                    active      = int(row["active_count"]),
                    active_eth  = float(row["active_eth"]),
                    entry_q     = int(row["entry_count"]),
                    exit_q      = int(row["exit_count"]),
                    exit_eth    = float(row["exit_eth"]),
                    pending     = int(row.get("pending_deposits_count") or 0),
                    pending_eth = float(row.get("pending_deposits_eth") or 0),
                )
    return {ep: d for ep, d in raw.items() if d["active"] > 0}   # drop missed slots


# ─────────────────────────────────────────────────────────────────────────────
# 1. Deterministic queue simulation
# ─────────────────────────────────────────────────────────────────────────────

def simulate_queues(
    initial_active: int,
    entry_q: int,
    exit_q: int,
    pending: int,
    activation_rate: int = ACTIVATION_RATE,
    drain_rate: int = DRAIN_RATE,
    max_epochs: int = 30_000,
) -> list:
    """
    Simulate epoch-by-epoch until all queues reach zero.

    pending is treated as 'new-validator deposits' (upper-bound scenario).
    Returns list of dicts {epoch_offset, active, entry_q, exit_q, pending}.
    """
    ac, eq, xq, pq = initial_active, entry_q, exit_q, pending
    rows = [dict(epoch_offset=0, active=ac, entry_q=eq, exit_q=xq, pending=pq)]

    for offset in range(1, max_epochs + 1):
        # Exit completions: validators whose exit_epoch arrived.
        # Does NOT change active_count (they left when their exit was scheduled).
        xq = max(0, xq - drain_rate)

        # Activations from entry_q, then from pending.
        available = eq + pq
        acts      = min(activation_rate, available)
        from_eq   = min(acts, eq)
        from_pq   = acts - from_eq
        eq        = max(0, eq - from_eq)
        pq        = max(0, pq - from_pq)
        ac       += acts

        rows.append(dict(epoch_offset=offset, active=ac,
                         entry_q=eq, exit_q=xq, pending=pq))
        if eq == 0 and xq == 0 and pq == 0:
            break

    return rows


# ─────────────────────────────────────────────────────────────────────────────
# 2. Per-epoch delta extraction and distribution building
# ─────────────────────────────────────────────────────────────────────────────

def extract_epoch_deltas(epoch_data: dict, max_gap: int = 5) -> tuple:
    """
    Compute per-epoch delta_active for all consecutive epoch pairs.

    Returns a named tuple of four lists + event_rate:
      steady_deltas   – delta values when entry_q = 0 AND exit_q < 30 AND |Δ| ≤ CAP
                        (true post-queue steady state; best for projecting after queues clear)
      organic_deltas  – all delta values with |Δ| ≤ CAP (includes entry-queue activation bias)
      event_deltas    – delta values < -ORGANIC_DELTA_CAP  (large batch exits)
      event_rate      – fraction of ALL epochs that are event epochs
    """
    epochs  = sorted(epoch_data)
    steady  = []   # quiet: no queues running
    organic = []   # all non-event
    events  = []

    for i in range(1, len(epochs)):
        ep, prev_ep = epochs[i], epochs[i - 1]
        if ep - prev_ep > max_gap:
            continue
        prev  = epoch_data[prev_ep]
        delta = epoch_data[ep]["active"] - prev["active"]

        if delta < -ORGANIC_DELTA_CAP:
            events.append(delta)
        else:
            organic.append(delta)
            # Steady-state: no pending activation pipeline, no large exit queue
            if prev["entry_q"] == 0 and prev["exit_q"] < 30:
                steady.append(delta)

    total    = len(organic) + len(events)
    evt_rate = len(events) / total if total else 0.0
    return steady, organic, events, evt_rate


def build_daily_distribution(per_epoch_deltas: list,
                              n_synth: int = N_SYNTH_DAYS,
                              seed: int = 123) -> list:
    """
    Bootstrap: generate n_synth synthetic daily deltas by summing
    EPOCHS_PER_DAY (225) i.i.d. samples from per_epoch_deltas.

    This approximates the distribution of 1-day active_count changes
    under the assumption that the per-epoch deltas are drawn from
    the given empirical distribution.
    """
    rng   = random.Random(seed)
    daily = []
    for _ in range(n_synth):
        total = sum(rng.choices(per_epoch_deltas, k=EPOCHS_PER_DAY))
        daily.append(total)
    return daily


# ─────────────────────────────────────────────────────────────────────────────
# 3. Monte Carlo
# ─────────────────────────────────────────────────────────────────────────────

def monte_carlo(
    initial_active: int,
    daily_dist: list,
    n_sims: int = N_SIMS,
    horizon_days: int = HORIZON_DAYS,
    seed: int = 42,
) -> dict:
    """
    Bootstrap Monte Carlo: each simulated day samples one value from daily_dist.
    Returns {output_day: sorted list of active_count across all simulations}.
    """
    rng = random.Random(seed)
    output_days = [d for d in (1, 7, 14, 30, 60, 90, 180, 365) if d <= horizon_days]
    results: dict = {d: [] for d in output_days}

    for _ in range(n_sims):
        active = initial_active
        for day in range(1, horizon_days + 1):
            active += rng.choice(daily_dist)
            if day in results:
                results[day].append(active)

    for d in output_days:
        results[d].sort()

    return results


# ─────────────────────────────────────────────────────────────────────────────
# 4. CSV output helpers
# ─────────────────────────────────────────────────────────────────────────────

def save_deterministic_csv(sim_a: list, sim_b: list, last_epoch: int):
    last_dt    = epoch_to_dt(last_epoch)
    b_by_off   = {r["epoch_offset"]: r for r in sim_b}
    a_by_off   = {r["epoch_offset"]: r for r in sim_a}
    max_offset = sim_b[-1]["epoch_offset"]
    step       = max(1, EPOCHS_PER_DAY)

    os.makedirs(DATA_DIR, exist_ok=True)
    with open(DET_CSV, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["epoch_offset", "date_utc",
                    "active_A_queues_only", "active_B_all_pending",
                    "entry_q_B", "exit_q_B", "pending_B"])
        off = 0
        while off <= max_offset:
            dt = last_dt + timedelta(seconds=off * SECONDS_PER_EPOCH)
            ra = a_by_off.get(off, sim_a[-1])
            rb = b_by_off.get(off, sim_b[-1])
            w.writerow([off, fmt(dt),
                        ra["active"], rb["active"],
                        rb["entry_q"], rb["exit_q"], rb["pending"]])
            if off == max_offset:
                break
            off = min(off + step, max_offset)


def save_statistical_csv(mc_organic: dict, mc_full: dict,
                         last_epoch: int, det_epochs_b: int):
    base_dt = epoch_to_dt(last_epoch) + timedelta(
        seconds=det_epochs_b * SECONDS_PER_EPOCH
    )
    os.makedirs(DATA_DIR, exist_ok=True)
    with open(STAT_CSV, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["day_from_det_end", "date_utc",
                    "organic_p5", "organic_p25", "organic_p50",
                    "organic_p75", "organic_p95",
                    "full_p5", "full_p25", "full_p50",
                    "full_p75", "full_p95"])
        for day in sorted(mc_organic):
            dt = base_dt + timedelta(days=day)
            vo = mc_organic[day]
            vf = mc_full[day]
            w.writerow([day, fmt(dt),
                        round(pct(vo, 5)),  round(pct(vo, 25)), round(pct(vo, 50)),
                        round(pct(vo, 75)), round(pct(vo, 95)),
                        round(pct(vf, 5)),  round(pct(vf, 25)), round(pct(vf, 50)),
                        round(pct(vf, 75)), round(pct(vf, 95))])


# ─────────────────────────────────────────────────────────────────────────────
# 5. Main
# ─────────────────────────────────────────────────────────────────────────────

def main():
    epoch_data   = load_epoch_data(HISTORY_CSV)
    valid_epochs = sorted(epoch_data)
    last_epoch   = valid_epochs[-1]
    first_epoch  = valid_epochs[0]
    last         = epoch_data[last_epoch]
    n_hist_days  = (last_epoch - first_epoch) * SECONDS_PER_EPOCH / 86400

    # ── Deterministic simulation ──────────────────────────────────────────────
    sim_a = simulate_queues(   # Scenario A: existing queues only
        initial_active=last["active"], entry_q=last["entry_q"],
        exit_q=last["exit_q"],         pending=0,
    )
    sim_b = simulate_queues(   # Scenario B: all pending deposits activate
        initial_active=last["active"], entry_q=last["entry_q"],
        exit_q=last["exit_q"],         pending=last["pending"],
    )
    det_epochs_b = sim_b[-1]["epoch_offset"]
    det_days_b   = det_epochs_b * SECONDS_PER_EPOCH / 86400

    # ── Per-epoch delta distributions ─────────────────────────────────────────
    steady_ep, organic_ep, event_ep, event_rate_ep = extract_epoch_deltas(epoch_data)

    # Full distribution (all epochs mixed proportionally)
    all_ep = organic_ep + event_ep

    print(f"Per-epoch delta samples:  steady={len(steady_ep)}  "
          f"organic={len(organic_ep)}  event={len(event_ep)}  "
          f"event_rate={event_rate_ep:.1%}")

    # Build synthetic daily distributions via bootstrap
    print("Building synthetic daily distributions…", flush=True)
    # Use steady for the "quiet" lower-bound; use all_ep for the "full history" upper-bound.
    # Fall back to organic if steady has too few samples.
    steady_source = steady_ep if len(steady_ep) >= 50 else organic_ep
    steady_daily  = build_daily_distribution(steady_source)
    full_daily    = build_daily_distribution(all_ep)

    # ── Monte Carlo ───────────────────────────────────────────────────────────
    # Statistical phase starts after queues from Scenario B are cleared.
    # For Scenario A, queues are already empty, so statistical phase starts now.
    print(f"Running Monte Carlo ({N_SIMS:,} simulations × {HORIZON_DAYS} days)…", flush=True)
    initial_b = sim_b[-1]["active"]

    mc_steady = monte_carlo(initial_b, steady_daily, N_SIMS, HORIZON_DAYS, seed=42)
    mc_full   = monte_carlo(initial_b, full_daily,   N_SIMS, HORIZON_DAYS, seed=42)

    # Also run for Scenario A (queues already empty, stat phase starts now)
    initial_a    = sim_a[-1]["active"]
    mc_a_steady  = monte_carlo(initial_a, steady_daily, N_SIMS, HORIZON_DAYS, seed=42)
    mc_a_full    = monte_carlo(initial_a, full_daily,   N_SIMS, HORIZON_DAYS, seed=42)

    # ── Save CSVs ─────────────────────────────────────────────────────────────
    save_deterministic_csv(sim_a, sim_b, last_epoch)
    save_statistical_csv(mc_steady, mc_full, last_epoch, det_epochs_b)

    # ── Print report ──────────────────────────────────────────────────────────
    SEP = "=" * 74

    print()
    print(SEP)
    print("VALIDATOR CHURN ANALYSIS")
    print(SEP)
    print(f"History  : {fmt(epoch_to_dt(first_epoch))} → "
          f"{fmt(epoch_to_dt(last_epoch))}  "
          f"({n_hist_days:.0f} days,  {len(valid_epochs)} epochs)")
    print(f"⚠ Small sample: results are indicative, not statistically robust.")

    # ── Current state ─────────────────────────────────────────────────────────
    print(f"\nCURRENT STATE  (epoch {last_epoch}, "
          f"{fmt(epoch_to_dt(last_epoch))})")
    print(f"  Active validators  : {last['active']:>10,}")
    print(f"  Active ETH         : {last['active_eth']:>14,.0f} ETH")
    print(f"  Entry queue        : {last['entry_q']:>10,}  validators  "
          f"(activates at {ACTIVATION_RATE}/epoch)")
    print(f"  Exit queue         : {last['exit_q']:>10,}  validators  "
          f"(drains at {DRAIN_RATE}/epoch, no further Δ to active_count)")
    print(f"  Pending deposits   : {last['pending']:>10,}  deposits   "
          f"({last['pending_eth']:,.0f} ETH)")

    # ── Historical distributions ──────────────────────────────────────────────
    print(f"\nHISTORICAL PER-EPOCH DELTA DISTRIBUTION")
    print(f"  Organic epochs  (|Δ| ≤ {ORGANIC_DELTA_CAP}): {len(organic_ep):,}  "
          f"—  mean={statistics.mean(organic_ep):+.2f}, "
          f"stdev={statistics.stdev(organic_ep) if len(organic_ep)>1 else 0:.2f}, "
          f"range=[{min(organic_ep):+d}, {max(organic_ep):+d}]")
    print(f"  Event epochs    (Δ < -{ORGANIC_DELTA_CAP}):  {len(event_ep):,}  "
          f"—  mean={statistics.mean(event_ep):+.1f}, "
          f"range=[{min(event_ep):+d}, {max(event_ep):+d}]")
    print(f"  Event rate: {event_rate_ep:.1%} of epochs  "
          f"(≈{event_rate_ep*EPOCHS_PER_DAY*365:.0f} event-epochs/year)")

    # Synthetic daily distributions summary
    steady_daily_sorted = sorted(steady_daily)
    full_daily_sorted   = sorted(full_daily)
    print(f"\n  Synthetic daily delta (from {N_SYNTH_DAYS:,} bootstrap samples):")
    print(f"    Steady-state:  "
          f"p5={pct(steady_daily_sorted,5):+.0f}  "
          f"p50={pct(steady_daily_sorted,50):+.0f}  "
          f"p95={pct(steady_daily_sorted,95):+.0f}  "
          f"per day  (source: {len(steady_source)} epochs, entry_q=0)")
    print(f"    Full history:  "
          f"p5={pct(full_daily_sorted,5):+.0f}  "
          f"p50={pct(full_daily_sorted,50):+.0f}  "
          f"p95={pct(full_daily_sorted,95):+.0f}  "
          f"per day")

    # ── Deterministic projection ──────────────────────────────────────────────
    print(f"\n{SEP}")
    print("DETERMINISTIC QUEUE PROJECTION")
    print(SEP)

    fa = sim_a[-1]
    fb = sim_b[-1]
    last_dt = epoch_to_dt(last_epoch)

    print(f"\nScenario A — exit + entry queues only  (pending NOT included)")
    print(f"  Queues clear in:  {fa['epoch_offset']} epochs  "
          f"({fa['epoch_offset'] * SECONDS_PER_EPOCH / 86400:.1f} days)")
    print(f"  Final active:     {fa['active']:,}  "
          f"(Δ {fa['active'] - last['active']:+,})")

    print(f"\nScenario B — all pending deposits activate  (upper bound)")
    print(f"  Queues clear in:  {det_epochs_b:,} epochs  ({det_days_b:.0f} days)")
    print(f"  Final active:     {fb['active']:,}  "
          f"(Δ {fb['active'] - last['active']:+,})")
    print(f"  Final ETH:        ~{last['active_eth'] + last['pending_eth']:,.0f} ETH")

    print(f"\n  Milestone table  (Scenario B, {ACTIVATION_RATE} activations/epoch):")
    print(f"  {'Day':>5}  {'Date':>10}  {'Active':>10}  {'Pending left':>14}  {'Entry q':>8}  {'Exit q':>7}")
    b_by_off   = {r["epoch_offset"]: r for r in sim_b}
    target_days = [0, 7, 14, 21, 28]
    target_days += [d for d in range(30, int(det_days_b) + 1, 30)]
    target_days.append(int(det_days_b))
    seen = set()
    for d in sorted(set(target_days)):
        if d in seen:
            continue
        seen.add(d)
        off_target = round(d * EPOCHS_PER_DAY)
        if off_target > det_epochs_b:
            off_target = det_epochs_b
        # Find closest epoch_offset in sim_b
        r = b_by_off.get(off_target)
        if r is None:
            closest = min(b_by_off, key=lambda o: abs(o - off_target))
            r = b_by_off[closest]
        actual_day = r["epoch_offset"] * SECONDS_PER_EPOCH / 86400
        dt         = last_dt + timedelta(seconds=r["epoch_offset"] * SECONDS_PER_EPOCH)
        print(f"  {actual_day:>5.0f}  {fmt(dt):>10}  "
              f"{r['active']:>10,}  {r['pending']:>14,}  "
              f"{r['entry_q']:>8,}  {r['exit_q']:>7,}")

    # ── Statistical projection ────────────────────────────────────────────────
    print(f"\n{SEP}")
    print(f"STATISTICAL PROJECTION  (Monte Carlo, {N_SIMS:,} sims, "
          f"starts after Scenario B deterministic horizon)")
    print(SEP)

    def print_mc_table(mc_organic_r, mc_full_r, base_dt, initial):
        print(f"\n  Initial active at start of statistical phase: {initial:,}")
        print(f"  {'Day':>5}  {'Date':>10}"
              f"  {'sdy p5':>8}  {'sdy p50':>8}  {'sdy p95':>8}"
              f"  {'full p5':>8}  {'full p50':>8}  {'full p95':>8}")
        for day in sorted(mc_organic_r):
            dt  = base_dt + timedelta(days=day)
            vo  = mc_organic_r[day]
            vf  = mc_full_r[day]
            print(f"  {day:>5}  {fmt(dt):>10}"
                  f"  {pct(vo,5):>8,.0f}  {pct(vo,50):>8,.0f}  {pct(vo,95):>8,.0f}"
                  f"  {pct(vf,5):>8,.0f}  {pct(vf,50):>8,.0f}  {pct(vf,95):>8,.0f}")

    # Scenario A stat projection (queues already empty, starts today)
    print(f"\nScenario A  (stat phase starts today, {fmt(last_dt)})")
    print_mc_table(mc_a_steady, mc_a_full, last_dt, initial_a)

    # Scenario B stat projection (starts after all pending activate)
    base_dt_b = last_dt + timedelta(seconds=det_epochs_b * SECONDS_PER_EPOCH)
    print(f"\nScenario B  (stat phase starts {fmt(base_dt_b)}, "
          f"after all pending activate)")
    print_mc_table(mc_steady, mc_full, base_dt_b, initial_b)

    print(f"\n{SEP}")
    print(f"Saved: {DET_CSV}")
    print(f"Saved: {STAT_CSV}")
    print(f"\nColumn guide:")
    print(f"  steady = steady-state distribution  "
          f"(entry_q=0, exit_q<30 — lower volatility bound)")
    print(f"  full = full history distribution   "
          f"(includes turbulent exit wave — upper volatility bound)")
    print(SEP)


if __name__ == "__main__":
    main()
